# Code Flow CryoSat-2 Machine Learning
## 19th Sept 2018
### Sanggyune Lee, Claude de Rijke, Isobel Lawrence, Maud van Soest, Harry Heorton, Steve Something

In [ ]:
# New ipynb for us to do ML
# what modules do we need?

import pandas

In [ ]:
## Read the csv file of training data:
training_data = pandas.read_csv('C:\Users\ste_j\Desktop\UCL-Test\Github\Cryo-Lead-ML\Individual_RF.csv')

train_x = data[['STD','Skew','kurtosis','PP','Sigma']]
train_y = data [['Class']]

In [ ]:
# read in the hdf files

In [ ]:
# read in the ESA schemes for CryoSat

In [ ]:
# data editting and formatiing

In [ ]:
# run the machie learning
# what scheme to use.... tensor flow maybe?

In [1]:
# plot something


In [55]:
import csv
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.optimizers import RMSprop, adam
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
import pandas as pd

In [73]:

data_frame = pd.read_csv('Individual_RF.csv')
all_classes = data_frame['Class'].values
all_features = data_frame.drop('Class', axis=1).values

one_hot_flat = []
for label in all_classes:
    if label =='lead':
        one_hot_flat.extend([1,0,0])
    if label =='ice':
        one_hot_flat.extend([0,1,0])
    if label=='ocean':
        one_hot_flat.extend([0,0,1])
print(np.shape(one_hot_flat)[0])
#making an array of shape [[, , ],[, , ], ...]
one_hot_labels = np.reshape(one_hot_flat, (int(round(np.shape(one_hot_flat)[0]/3)), 3)) 
print(np.shape(one_hot_reshaped))
print(one_hot_labels[4000:4005])


14580
(4860, 3)
[[0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]]


In [74]:
def create_model():
    model = Sequential()
    #adding 400 nodes to the shallow layer:
    model.add(Dense(400, input_dim=int(5), kernel_initializer='normal', activation='relu'))
    model.add(Dropout(0.2))
    # Another hidden layer of 16 units
    model.add(Dense(16, kernel_initializer='normal', activation='relu'))
    #output layer
    model.add(Dense(3, kernel_initializer='normal', activation='softmax'))
    # Compile model
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

In [76]:
# Wrap our Keras model in an estimator compatible with scikit_learn
estimator = KerasClassifier(build_fn=create_model, epochs=30, verbose=0)
# Now we can use scikit_learn's cross_val_score to evaluate this model identically to the others
cv_scores = cross_val_score(estimator, all_features, one_hot_labels, cv=15) # cv = train test split (k-1: 1)
cv_scores.mean()



0.9141975308641975

In [ ]:
#Shallow (400 nodes), 'relu', 20% dropout, activation = softmax, optimizer = adam, cv = 10 : 0.889094650156704
#deep1 (400 nodes, 16 nodes), 'relu', 20% dropout, activation = softmax, optimizer = adam, cv = 10 : 0.913168724230778
##deep2 (400 nodes, 16 nodes, 16 nodes), """": 0.8946502056877309
#deep1 (400 nodes, 16 nodes), 'relu', 20% dropout, activation = softmax, optimizer = adam, cv = 5 : 0.7382716049934611
# " cv = 15: 0.9141975308641975